# Conexão com o banco do XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_logistica
spring.datasource.username=root
spring.datasource.password=

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true